### ISSUE TITLE
What ids we should use?

### ISSUE THREAD

**Issue by Integral** [substance/archivist#1]
Hello @michael and @oliver---- !

Let's think what we'll use as id: substance internal generated id or mongo object id.

I know that you already thought over using mongo's id, but what are pros and cons here?

I just discovered that we'll run into problems with making new subject (not saved yet) parent of anything, because it haven't got any id, so parent property of child would be empty. Maybe we should use internal generator?

**Comment by michael** [comment]
Isn't this resolved already?

**Comment by Integral** [comment]
definitely
