### ISSUE TITLE
Remarks so slow...

### ISSUE THREAD

**Issue by Integral** [substance/archivist#109]
@michael, I just commit example of slow remarks to composer repo. It's really super slow... Sometimes it takes 20-30 seconds for remark highlighting...
Use ```var EXAMPLE_DOC = require("../data/big_sample_remarks");```inside ```local_backend.js```

**Comment by michael** [comment]
thanks! 

just give me some time for this - i need to convert codebase to new writer first.

**Comment by michael** [comment]
fixed with new comments implementation. (I hope so)
