### ISSUE TITLE
Store comments outside of interview

### ISSUE THREAD

**Issue by michael** [substance/archivist#113]
I finished the first iteration of the embeddable HtmlEditor, that we can use to edit comments. We would now be able to fetch comments asynchronously, as we do it with our entities etc. In the document you would have just comment_references.

@Integral can you develop an API for creating, updating and deleting comments?

We will also need to touch the document schema, so there will be some conversion needed if you want to preserve the existing comments from current interviews.

**Comment by Integral** [comment]
Please reactivate it if you still need this.
