### ISSUE TITLE
Ghost selection appeared after undoing subject tagging

### ISSUE THREAD

**Issue by Integral** [substance/archivist#118]
Steps to reproduce:
1. Select something and press subject tool
2. Do cmd-z for a while
3. Place cursor outside of selection 

![](http://g.recordit.co/cH0ZePpv8g.gif)

**Comment by Integral** [comment]
UPD: It's saved as subject annotation despite it was visually removed.

**Comment by oliver----** [comment]
Problem is, that the react components do not get rerendered properly.

**Comment by oliver----** [comment]
Fixed.

Was actually a similar problem as #119
