### ISSUE TITLE
Undoing multiannotation leads to error

### ISSUE THREAD

**Issue by Integral** [substance/archivist#119]
Steps to reproduce:
1. Select more then one para and click multiannotation tool (subject or comment tool)
2. Press cmd-z for a while 
you'll get ```Uncaught TypeError: Cannot read property 'get' of null```

![](http://g.recordit.co/itlBdSvZ4p.gif)

**Comment by Integral** [comment]
The same situation would be even if you'll leave annotation panel. It just fails and then editor starts new joyful life with errors everywhere.

**Comment by oliver----** [comment]
The problem is: app state still is referencing (highlighting) the annotation, which is removed by undo,
leading to an invalid situation in TextProperty.

Adding a workaround to TextProperty.
But the origin of the problem should be addressed somehow @michael

**Comment by oliver----** [comment]
Sorry, the previous analysis was rubbish.

**Comment by oliver----** [comment]
Fixed.
