### ISSUE TITLE
Locations/persons/glossary next steps

### ISSUE THREAD

**Issue by michael** [substance/archivist#12]
Daniel, how should we move on here? We use static test data for location entries, persons etc.

Option1: Connect those to the database
Option2: Disable those panels and annotation tools for the time being, and only provide subject tagging for the January Archivist release.

**Comment by Integral** [comment]
I think we should focus mostly on subjects. Would be better to make subjects more friendly. We discussed possibility of adding new subjects right from the editor, let's focus on this rather on other entities.

**Comment by michael** [comment]
OK. I will disable those extensions for now. Now that we are in web mode, creating subject from editor could be an option. Need to think a bit.
