### ISSUE TITLE
Wrong selections

### ISSUE THREAD

**Issue by Integral** [substance/archivist#120]
@oliver---- 
look carefully at the first frames
![](https://camo.githubusercontent.com/423378cd4116d991d2f607c555169c756f09c15f/687474703a2f2f672e7265636f726469742e636f2f6348305a6550707638672e676966)
I'm doing selection and the first 10 symbols just cutting during this process... It's really sometimes happened...

After some discovering I could say that it probably happened when you place cursor first time inside document. And sometime it could just don't create selection at all...

**Comment by oliver----** [comment]
Don't get it... is the problem that after setting the cursor the toolbar is not enabled correctly?

**Comment by Integral** [comment]
@oliver---- take a look at these frames:
![](http://cl.ly/image/1b2e2P0F021G/selbug1.jpg)
![](http://cl.ly/image/1S0n0J2k2z2v/selbug2.jpg)
![](http://cl.ly/image/0H0H2I0Y1A1H/selbug3.jpg)
So it's dropped out everything that was on the left of cursor.

**Comment by oliver----** [comment]
Strange... it doesn't do this for me...

So what you do is
1. set the cursor
2. select a range starting before the cursor and ending behind
Then the resulting selection is truncated at the position of the former cursor position.
Right?

**Comment by oliver----** [comment]
Ah... it seems to occur only the first time after the document was loaded.

**Comment by Integral** [comment]
Right. But it's not happens everytime. I think it's happens only if you set cursor in container for the first time and if you'll do it quickly. But I'm not sure. I think I need to test more. But maybe you could tell me what and where I could console to get evidence?

**Comment by oliver----** [comment]
And I think I know why... again react related.

**Comment by Integral** [comment]
Hope we can figure out these react issues...

**Comment by oliver----** [comment]
Yep... Michael and me were discussing yesterday about it and we will work on it together this evening.

**Comment by Integral** [comment]
Fine!

**Comment by oliver----** [comment]
@michael for the records: another one caused by the slow state transition, respectively, the TextProperty.shouldComponentUpdate calls.

**Comment by michael** [comment]
yeah we should really do something here

**Comment by michael** [comment]
let's discuss in the evening!

**Comment by oliver----** [comment]
Will be better when #126 is done.

**Comment by oliver----** [comment]
This should be ok now.
