### ISSUE TITLE
Emit event after rendering document

### ISSUE THREAD

**Issue by Integral** [substance/archivist#124]
Please emit document:loaded event after loading completed.
We need this to stop progress bar which is now stopping after receiving document from database which is much earlier than user can start to work.
We will also use this for counting rendering time. On my mac it takes 10 seconds for four hours transcription. This is probably means that on windows machines that could be much longer.

**Comment by michael** [comment]
where should i emit this event? like to which object you want to bind an event handler to?

**Comment by Integral** [comment]
to doc

**Comment by michael** [comment]
ok i consider this more a hack, but i will trigger a document:rendered event on the doc..

**Comment by michael** [comment]
Done: https://github.com/substance/archivist-core/commit/f118c0f2fe69e2f005f9b055102dd182fbbde0a2

**Comment by michael** [comment]
you bind with `document.connect(this, {'document:rendered': myhandler})`.
