### ISSUE TITLE
Subjects toc bad permormance

### ISSUE THREAD

**Issue by Integral** [substance/archivist#125]
Currently in some cases it's taking more than 10 seconds to highlight subjects.

**Comment by oliver----** [comment]
Maybe will be improved by #126

**Comment by michael** [comment]
need to check here how much time the computation of the highlights takes as well as the re-render of toc_tree component.

**Comment by michael** [comment]
i will first look into the bigger problems related to #126 tomorrow. Not sure if i will be able to fix this too. I make this a lower priority now. also because i think it will speed up anyway when #126 is resolved.

**Comment by michael** [comment]
Much faster now with new approach (#126)
