### ISSUE TITLE
Consider improved subject creation / annotation workflow

### ISSUE THREAD

**Issue by michael** [substance/archivist#13]
- Should allow creation of subjects ad-hoc
- how hard is it to implement reordering of subjects right in that editor panel?
- could it replace the current subject manager entirely? (does this make sense after all?)

@Integral what did you find out about drag and drop so far? I could imagine this working very nicely for daily work when combined into the editor. The question is how high is the price to do it, and when we should do it? If you are close to finish with the external subject manager I do this work after the January release. If you think it would significantly improve the UI we should talk before you continue so you we don't do the work twice.

**Comment by Integral** [comment]
Oh, sorry, i was playing with dnd right before getting sick, will continue tomorrow. I'm already created some shadow containers when you drag: https://archivist-app.herokuapp.com/subjects, the main problem that i couldn't catch ```drop``` event. Very strange.

**Comment by Integral** [comment]
oh and i think that we do not need dragging inside editor panel, we only need adding because it will popular operation during working with text and it'll be not good to go somewhere and lose current state to add new term

**Comment by michael** [comment]
The thing is that just creating a new entry immediately requires setting the parent or reordering. Not sure what we should do here.

The only idea i have is having little plus icons next to each tree entry for creating. I will make sketches later for improved subjects edit dialog.

**Comment by Integral** [comment]
I think that plus icon separated from the tree with parent selection would be nice.

**Comment by Integral** [comment]
phoooooff
now dnd basically working, i need to hide currently draggable item and add possibility to make term root

**Comment by Integral** [comment]
closing #5
draggable subjects is working now, just as old variant with button, i also added new button for making parent root.

**Comment by Integral** [comment]
closing #2
now we have more or less but workflow, and i'll try to update real world examples
we also need to define some bar for notifications

**Comment by michael** [comment]
Are we safe to merge the editor integration stuff into master?

**Comment by Integral** [comment]
I hope so... Let's try?

**Comment by michael** [comment]
Will do

**Comment by michael** [comment]
I tried but messed up. Today is not my day...  there's a conflict in public/platform/index.js. Maybe you can try? I have to go now :/

**Comment by Integral** [comment]
Oh, it seems that i did this but in your branch :(

**Comment by michael** [comment]
i synced master and pushed.. from now on we can work with master.

**Comment by michael** [comment]
I will look into this soon. I need your input on what API to use for creating new a new subject. 

I will try to integrate the nestable widget and restyle it a bit. @Integral what's your feeling about using nestable for the subject admin tool atm? hop on skype if you want to discuss a bit.

**Comment by Integral** [comment]
@michael hey!
current state of things, have bad and good news.
Good news are that i was able to add import feature, it's textarea field where you could paste name of subjects with hierarchy (using tabs). And now we have all 788 subjects in db!
Bad news are that I can not easily edit subject now. Do you remember our ```updateHiercharchy``` function? It runs when i change title of subject, after every operation like adding one letter. So you typing subject and you run this function multiple times. But it seems that now with 788 items it's not so fast process... We need to change it. Have you got any ideas?

**Comment by michael** [comment]
we don't need this now.
