### ISSUE TITLE
Enable CORS for some public API's

### ISSUE THREAD

**Issue by michael** [substance/archivist#137]
@Integral can you enable CORS so i can use the latest subjects and entity data in the archivist-dev environment?

instead of a static fixture it would be nice to fetch it from the server e.g. 

http://ost.d4s.io/api/subjects?page=1&sort_by=position&order=asc

However that is currently not possible because of:

XMLHttpRequest cannot load http://ost.d4s.io/api/subjects?page=1&sort_by=position&order=asc. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access.
backend.js:82 undefinedBackend.Prototype.getSubjects.$.ajax.error @ backend.js:82n.Callbacks.j @ jquery-2.1.3.min.js:2n.Callbacks.k.fireWith @ jquery-2.1.3.min.js:2x @ jquery-2.1.3.min.js:4n.ajaxTransport.k.cors.a.crossDomain.send.b @ jquery-2.1.3.min.js:4

**Comment by Integral** [comment]
done

**Comment by michael** [comment]
thanks!
