### ISSUE TITLE
Time marks

### ISSUE THREAD

**Issue by michael** [substance/archivist#15]
@Integral you would like to have that in right? Maybe I can come up with a really quick and dirty solution to stick time marks to paragraphs. We only track the time of the beginning of the para, it ends when the next time mark is seen. That way we don't have to input from-to values.

**Comment by Integral** [comment]
yeah, that would be nice!

**Comment by michael** [comment]
just wonder if we should make another panel for that? I guess that's a bit too much? We will get a lot of panels...

Is it important to have the time marks listed so you can jump to the positions in the text?

More quick and dirty would be a workflow showing a popup or temporary overlay of sidebar.

**Comment by Integral** [comment]
Currently it's not important.

**Comment by michael** [comment]
Implementing this on text node (paragraph) and store time data on that text node.. that's a bit hacky but should be fine for now to capture the data. And we can try out the UI for it. Will be reimplemented at a later time.

**Comment by michael** [comment]
I hacked some interface today.. but I'm not satisfied with it, since it clutters the interface way too much and adds confusion.

![image](https://cloud.githubusercontent.com/assets/2931/5760016/1c4cbe92-9cd2-11e4-8b46-9f270f6af4bc.png)

Maybe you have ideas (sketches welcome)

- is there an alternative to showing time mark toggles for each content node (paragraph)?
- how we visually distinguish when a timemark has been set for a node and when not? we should have that timemark rendered somehow
- where should the control be displayed to edit the time mark.. I don't like it to take space in the resource panel

@Integral is it necessary that the time marks shows up right next to the text when it has been set..  or is it fine to be revealed after clicking some button or navigating through the text with the cursor?

**Comment by michael** [comment]
Maybe we could move the time mark editing into the content tools bar.. e.g. when cursor is over paragraph it will give you the option to set/edit a timemark in the content tools bar.

Could look like this:

![image](https://cloud.githubusercontent.com/assets/2931/5760458/0ac94fd4-9cd5-11e4-92c2-940ba9607b07.png)

The thing I'm worried with the implementation of this: When you click inside that textbox in the content tools bar to edit the timemark we will loose the selection in the document and thus the context will change. Is there a way we could solve this, @oliver---- ?

**Comment by Integral** [comment]
@michael it most be hidden
i personally most like last soution

**Comment by michael** [comment]
made last solution work basically.. but needs testing and better styles.

**Comment by michael** [comment]
Done.

**Comment by Integral** [comment]
@michael what if i'm not set time mark in one paragraph? is it saved 00:00:00 or just not saving any time?

**Comment by michael** [comment]
it's undefined until you start typing in that field..  however maybe we should make a validity checker.. also a button to remove time mark. is it important you think?

for now we can catch 'valid' time marks..  by performing a simple check.. if there's anything > 00:00:00 set...
