### ISSUE TITLE
Strip down cover view

### ISSUE THREAD

**Issue by michael** [substance/archivist#18]
- remove cover upload thing

@Integral do we need an abstract or should i also disable that?

**Comment by Integral** [comment]
we need abstract in two languages

**Comment by michael** [comment]
ah okay, so i leave it there for now and we add second abstract field. languages will be russian and english?

**Comment by Integral** [comment]
yeah

**Comment by michael** [comment]
Done for now. in future we move abstract editing into metadata panel.
