### ISSUE TITLE
Paste is broken in web version

### ISSUE THREAD

**Issue by michael** [substance/archivist#19]
@oliver---- can you look into that.. would be urgent.

**Comment by Integral** [comment]
@michael this is critical for adding real example

**Comment by oliver----** [comment]
Fixed.

Bonus: rich text can be copied from Microsoft Word.

**Comment by michael** [comment]
Copy text from document itself is not working now. external pastes are fine.

Word heading level 3 are imported correctly, but not level 1 headings.

**Comment by Integral** [comment]
is it fixes?

**Comment by oliver----** [comment]
Basically yes. Though it is still not yet perfect.
