### ISSUE TITLE
REST: Upsert subjects

### ISSUE THREAD

**Issue by Integral** [substance/archivist#2]
Make subjects rest api upsertable with replacing of client ids and parent references by mongos ids as discussed at #1.

**Comment by michael** [comment]
Isn't this resolved already?

**Comment by Integral** [comment]
I guess it's not, i'll finish with it later. It's for updating and creating data in one request... But I should firstly create that request.

**Comment by Integral** [comment]
So I decided to track changes and save only new and changed subjects one by one. Because of saving whole collection not a natural thing for backbone.js. Now BSON objectid also generated on client when you add new subject.
