### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by michael** [substance/archivist#21]
would maybe be a good thing.. i removed the warning when navigating back that there are unsaved changes because it's annoying.. however, we should somehow make sure that users don't loose their work and autosave every minute or so.. 

you agree?

**Comment by Integral** [comment]
i'm agree!

**Comment by michael** [comment]
there's a difficulty here: when autosave is done asynchronously then while it's saving you can type... but by typing you would trigger another autosave which is bad... in desktop composer saving was a blocking action so we didn't have this problem. however blocking is not an option because it would annoy the user that wants to write... so what we need to do is if during saving doc gets modified we need to wait until save is complete and then immediately schedule a new save that gets executed right after first save has finished.. but then you would end up in a long chain of saves... not good. we should be careful with saves because it takes a lot of bandwidth and server memory also.

more simple solution: autosave every 60s (only if there are local changes). would that be good enough?

**Comment by michael** [comment]
Implemented. Happens every 10s atm. Only saves if document has changes.
