### ISSUE TITLE
Overflow in subject manager items

### ISSUE THREAD

**Issue by michael** [substance/archivist#27]
![image](https://cloud.githubusercontent.com/assets/2931/5788628/2d9e0644-9e42-11e4-926d-069c3807b667.png)

If you remove the height property (currently 30px) for `.list li span` it can be fixed.

![image](https://cloud.githubusercontent.com/assets/2931/5788636/5d6bb600-9e42-11e4-85c0-67e15c15d73e.png)

**Comment by michael** [comment]
there's another overflow problem. the container `.list` which is floated left, exceeds the browser boundaries, because of 100% height, which does not consider the 70px of the top bar...

**Comment by Integral** [comment]
@michael currently i'm used extra padding to avoid this. Have you got any other ideas? Maybe we should also make this column wider, what do you think?
I also think about status bar in bottom, like editor have...
