### ISSUE TITLE
Subject delete and merge

### ISSUE THREAD

**Issue by michael** [substance/archivist#29]
Pls implement deletion and merge of subject and point me to the API code, I will implement the cleanup on all available documents.

**Comment by Integral** [comment]
There is already deletion: https://github.com/substance/archivist/blob/master/controllers/db.js#L159-L163
I'm not sure what to do here with manager. What must happen when I removing subject which has children?

**Comment by michael** [comment]
mhh well.. delete is a pretty hard action, when deleting a parent all childs and subchilds need to be deleted as well. you should display a warning.

Not sure if recursive deletion should be implemented on client or server. server would be safest i guess.

**Comment by michael** [comment]
figured out that instantiating a substance article at that point is not so easy and maybe also too much.. i will implement this in a more dumb way.. (using native json) for now. We will have to optimize later anyway.

**Comment by michael** [comment]
Can you connect a delete button really quick so i can test my doc updater stuff?

**Comment by Integral** [comment]
not now, i could do it after few hours

**Comment by Integral** [comment]
@michael remove subject now exists and working, but still not updating rendered tree

**Comment by Integral** [comment]
merge almost here
it's now print ```Let's merge 54b8f41ca868bc7ce175536f with 54bae9e6a868bc3ec7fb5ae6``` to console
so we need to define now server part to send requests to it with two ids as arguments
@michael any requests?

**Comment by michael** [comment]
That's fine for now I'll do the rest.

**Comment by michael** [comment]
wait.. can you implement stub functions on the server.. in db.js and rest.js? you can just always cb(null) for the moment.. i will fill in functionality.. just want it to be connected with the client.

**Comment by Integral** [comment]
ok, give me some time

**Comment by Integral** [comment]
ok, it's connected now
query from client and server receives ids

**Comment by Integral** [comment]
btw i add [superagent](https://github.com/visionmedia/superagent) for easy queries outside of backbone
