### ISSUE TITLE
Switch to SASS for styles in archivist

### ISSUE THREAD

**Issue by michael** [substance/archivist#30]
we only use basics for modularization.

**Comment by Integral** [comment]
do you want to switch platform too?

**Comment by michael** [comment]
What do you mean with platform? This improvement is not meant to be done in the next days.. more a placeholder for improved version.

**Comment by Integral** [comment]
```Platform``` is our code name for entity manager :)

**Comment by michael** [comment]
i don't understand. ;) wanna make skype call with me and oliver in 15 mins?

**Comment by michael** [comment]
i'm currently showing him around

**Comment by Integral** [comment]
oh, yeah!!!
