### ISSUE TITLE
Make deployment to heroku work again

### ISSUE THREAD

**Issue by michael** [substance/archivist#31]
Update package.json accordingly. We need a production setup, that has a bundled archivst.js file with all editor-related stuff, instead of our dev-setup on-the-fly serving etc.

**Comment by oliver----** [comment]
I will finish this today.

**Comment by oliver----** [comment]
My favorite solution ATM is using git submodules.
While I was neglegting this approach up to now, I find some liking for it now, as it is a clear way to manage versions of submodules.
Nevertheless, we have a problem: substance-composer is private - so we can't clone it from heroku.

@michael @Integral any thoughts?

**Comment by Integral** [comment]
@oliver---- served it static should we :) maybe

**Comment by oliver----** [comment]
hmmm... we also could go a purely bundled way, maybe including source-maps for now.

**Comment by Integral** [comment]
is it possible to generate one js file? maybe we could also use gulp here?

**Comment by oliver----** [comment]
ATM we use screwdriver to create single js+css etc.
For js, it is actually browserify. CSS is custom...
gulp could be nice...

**Comment by oliver----** [comment]
And in deployment we need to turn of the CJSServer and instead serve statically.

**Comment by Integral** [comment]
there is node.js variable ```process.env.NODE_ENV``` which could be either development or production, i'll use it work with oauth things, so we could switch off CJSServer when it's equal production

**Comment by oliver----** [comment]
@Integral you need to generalize the google oauth callback URL.
ATM it is hard coded localhost:5000 ...

**Comment by Integral** [comment]
not sure that understand you, i'll just used different credentials depends on NODE_ENV

**Comment by oliver----** [comment]
Ok.
Right now it is hard-coded for devmode: https://github.com/substance/archivist/blob/master/controllers/oauth.js#L9-L12

**Comment by Integral** [comment]
Yes, I know. I can't change it right now because of there is no deployment.

**Comment by oliver----** [comment]
I am just playing fiddling with heroku. Can I temporarily set valid credentials so that I can go further into the system. Or doesn't it make sense at all because other things need to be deployed first?

**Comment by oliver----** [comment]
FYI, I am using a different branch for the deploy experiments: "release"

**Comment by Integral** [comment]
@oliver---- check your email box

**Comment by michael** [comment]
Regarding substance-composer.. I wonder if making it open source is an option? not sure... @Integral does the grant you got for the archivist require the software to be released as open source completely?

**Comment by oliver----** [comment]
Atm I follow @Integral's suggestion, serving the bundle. Now we need to establish the switches for diferent environments.
For roll-out the assets need to be generated and checked in.
I tried to run gulp etc on-the-fly but did not succeed.

**Comment by oliver----** [comment]
Woring in branch https://github.com/substance/archivist/tree/release
Deployed: https://archivist-app.herokuapp.com/

**Comment by michael** [comment]
nice! Subject manager is missing styles.

**Comment by oliver----** [comment]
@michael can you point me to the source which need to be included in the bundle?

**Comment by michael** [comment]
The jstree styles are missing, in local dev env style.css is used here. 

https://github.com/substance/archivist/tree/master/client/platform/local_modules/jstree/dist/themes/default

I guess you better grab the minimized version.

**Comment by oliver----** [comment]
Hmmm. Not sure.
https://github.com/substance/archivist/blob/release/public/archivist.html#L18-L19
And it gets loaded...

**Comment by michael** [comment]
The subject manager doesn't serve the archivist.html file. Instead jade templates are used, and a single combined css file (duo.js workflow). But I don't know the details here... it just seems there's a difference between our local env and the deployed one.

**Comment by oliver----** [comment]
Hmmm.. then we need @Integral's advice

**Comment by oliver----** [comment]
Ah... yes clear... We need to force check in the public/platform folder for release... Until we find out how to make gulp as postinstall script work.

**Comment by michael** [comment]
sounds good. let's check those files in for now..

**Comment by oliver----** [comment]
Probably this could be a way: https://github.com/timdp/heroku-buildpack-nodejs-gulp

**Comment by Integral** [comment]
hey-hey-hey, i'm here

**Comment by Integral** [comment]
that's why there was no bundles in .gitignore
we could create another branch with different .gitignore

**Comment by Integral** [comment]
@michael, @oliver---- it seems that easy solution already exists, [we can just add npm ```postinstall``` script](https://devcenter.heroku.com/articles/nodejs-support#customizing-the-build-process), it most be just same as our ```prepare```

**Comment by oliver----** [comment]
I tried that but did not succeed. Maybe you can help me here?

**Comment by Integral** [comment]
of course, is there any bundle already?

**Comment by Integral** [comment]
@oliver---- could we chat anywhere?

**Comment by oliver----** [comment]
Do we have that REAMDE chat thingie still?

**Comment by oliver----** [comment]
aaahh ... lets skype

**Comment by michael** [comment]
group chat on skype? i'm busy with fixing this maintenance mode bug..

**Comment by oliver----** [comment]
or g+... anything you wish
