### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Integral** [substance/archivist#33]
@michael hey!
I'm not sure that we have a best solution for summaries. We have annotations more in scientific style, e.g. each one is ~ 2-3 pages of word document.

**Comment by michael** [comment]
hmm... in future maybe it should live in the resource panel.. but for now that's technically difficult.. because some things like annotations are tied to the left panel. What about making the abstract collapsible? We can change the style also so it's same text size as the rest of the document.

**Comment by Integral** [comment]
Could we change text size now?

**Comment by michael** [comment]
Abstract text is now at regular size.
