### ISSUE TITLE
Adding new paragraph scrolls upper

### ISSUE THREAD

**Issue by Integral** [substance/archivist#34]
Steps to reproduce:
1. Open [Interview mit Anna Miftachutdinova](http://localhost:5000/archivist.html#state=composer.main;0.path=54bd6c2a85d239a6084ce1d0;1.contextId=toc)
2. Set cursor after last dot
3. Hit enter

**Comment by michael** [comment]
@oliver this is the weird bug we already know about. It only happened in the web-version not within atom shell.

**Comment by oliver----** [comment]
Fixed.
