### ISSUE TITLE
Can't remove empty paragraphs

### ISSUE THREAD

**Issue by Integral** [substance/archivist#35]
Steps to reproduce:
1. Open [Interview mit Anna Miftachutdinova](http://localhost:5000/archivist.html#state=composer.main;0.path=54bd6c2a85d239a6084ce1d0;1.contextId=toc)
2. Set cursor after last dot
3. Hit enter few times
4. Try to remove newly created paragraphs

I see here different errors:
```Currently only text and heading nodes can be joined.```
```Unexpected value at position 2. Expected d1a4d15b4850161768f29f4839773ce0, found e9c83659096236a49f68b449f3c0965b```

I even can't set cursor in some of these empty paras - it disappears.

**Comment by michael** [comment]
Assigning this to Oli

**Comment by oliver----** [comment]
Hmmm. This works for me, actually. But there is the glitch with the scrolling.
