### ISSUE TITLE
paragraphs are shuffled

### ISSUE THREAD

**Issue by Integral** [substance/archivist#36]
Just opened document which consists of 4 paragraphs which I created few hours before. The order of paragraphs is shuffled. Second paragraph is on tale now. Third paragraph is second and second is third. This document called ```Интервью c Львом Глебовичем Мищенко``` [interview mit Lev Glebovich Mishenko]

**Comment by michael** [comment]
This is very weird. @oliver---- any chance that this could happen?

**Comment by oliver----** [comment]
I could not create a similar situation. Tried to write paragraphs, and also via copy and paste. We should see if this happens again.
@Integral how did you create the situation exactly? maybe the editor was already in a bad state?

**Comment by Integral** [comment]
i'll try to update interview again and discover this

**Comment by oliver----** [comment]
I just noticed that the cursor is not set correctly after pasting. Maybe this way it felt like shuffled.
Will fix it...

**Comment by michael** [comment]
closing this. reopen when it occurs again.
