### ISSUE TITLE
CRITICAL: We need a locking mechanism while managing subjects to prevent from data inconsitencies

### ISSUE THREAD

**Issue by michael** [substance/archivist#38]
Oliver and I were having a longer discussion about this this morning.

Why we need locking?

- when subjects are removed/merged docs will be affected
- it's not possible to use the subject manager while people are editing
- updating all docs after a merge for instance can take some time.. so we need to have one big sort of transaction, otherwise we will have broken data
- we need to communicate to users that we are in maintenance mode, so they stop working and know what's going on

Workflow for changing subjects:
- only admins have access to subject manager (for now only you daniel)
- before subject manager can be used system must be turned into maintenance mode
- make changes to subjects (rename, delete, merge)
- click save in subject manager brings up a dialog
    - step1: warn user that changes affect existing documents
    - step2: provide UI to make a backup of the whole database (so if something goes wrong we can restore it later)
   - step3: apply changes (changes are propagated to the documents and saved immediately, also _rev of document changes)
   - step4: inform admin to check affected documents (we can provide a ui with links to docs maybe to make this check easier)
   - step5: if admins says everything is fine.. system can be switched into normal mode again

- users that had a document open, that was affected by the subjects changes will not be able to save their changes... they will see a message: your changes are rejected because document on the server has a newer revision

I will create separate issues for what we need to do. However this is very crucial for the project we think... because data loss and inconsistencies are not tolerable..

**Comment by Integral** [comment]
OMG

**Comment by michael** [comment]
WOO! Done.
