### ISSUE TITLE
Hide Subject Manager from common interface

### ISSUE THREAD

**Issue by michael** [substance/archivist#39]
only admins should have access.

**Comment by michael** [comment]
Did you check for admin privilege, Daniel to show that button?

**Comment by Integral** [comment]
what's your opinion here? should we hide this during locking?
if there's no way currently to add terms through editor then we don't need to hide this for all except admins, because everybody would be admins in this case :)

**Comment by michael** [comment]
ugh.. everybody admin? sure?

**Comment by Integral** [comment]
the problem is that everybody from editors team needs to add new terms (i believe so)

**Comment by michael** [comment]
just want to avoid the subjects are managed by different users at the same time. even if it should be save now.

**Comment by Integral** [comment]
hmm, maybe i most hide it during locking?

**Comment by michael** [comment]
hmm... wouldn't make a big difference unless we implement polling. we would need to deactivate the interface of the admin panel. but in any way what we have now is not meant to be used concurrently. moving, renaming, etc would work but delete and merge... you better only have one responsible user who clicks those buttons.

**Comment by Integral** [comment]
good, so i will set access handler for context menu items, delete and merge will see only superuser

**Comment by michael** [comment]
what about this: every editor can access the admin interface.. but merge and delete ops are only available for the admin (which is only one person + you). really, deletes and merges should be moderated.. not just be one click away from the user.. that will hurt the whole experience.

**Comment by Integral** [comment]
that's what i mean

**Comment by michael** [comment]
perfect. can you prioritise the remaining issues for tomorrow? you think we are launchable?

**Comment by Integral** [comment]
will try, you have #31

**Comment by michael** [comment]
oliver is on #31.

**Comment by Integral** [comment]
so you want that i fix remaining issues tomorrow? it's possible i think

**Comment by michael** [comment]
Let's try to make a deploy tomorrow. I will test and collect bugs in the morning. or if you need help with anything, let me know.

**Comment by Integral** [comment]
ok!

**Comment by Integral** [comment]
Nikita confirmed, everyone must be able to create new and edit subjects. Remove and merge may be restricted to superuser.

**Comment by Integral** [comment]
done
