### ISSUE TITLE
Try to use new transaction implementation from substance-next

### ISSUE THREAD

**Issue by oliver----** [substance/archivist#46]
Now as I pasted a whole interview I realized that the long expected performance issue arises.
In substance-next I have implemented a much more effient solution which should be applicable here too (modulo some problems of course).

**Comment by oliver----** [comment]
@Integral also I see a problem with request size: 
````
 PUT http://localhost:5000/api/documents/54be9ba3ef0404d24c4209fa 413 (Request Entity Too Large)
````

**Comment by Integral** [comment]
oops
we could change max allowed size for body, it's 100kb by default
we should do ```app.use(express.bodyParser({limit: '1mb'}))```
what is substance-next?

**Comment by Integral** [comment]
now i see - it's long time to wait while whole article pasted
saving is done by second

**Comment by oliver----** [comment]
since some month I am working on improvements of the editor - basically a rewrite. As soon as it is ready I will replace the current one... or step by step.

**Comment by oliver----** [comment]
Some insght: ATM, there are two sources which cause troubles with large documents...
1. transactions: atm the whole document is cloned. In substance-next a Copy-on-write clone is used, i.e., cloning is only done for nodes/properties which are actually changed
2. event listener: atm everything which reacts on changes is stored in a classical list of observers (e.g. node views), which increases by the number of nodes, thus everything gets slower for larger articles. With substance-next I want to introduce optimizations here, e.g., almost all observers determine if an update is necessary on the basis of the node id. Instead of asking each node view if it needs to be updated they could be stored in a tree with alpha-numeric keys,

**Comment by Integral** [comment]
what problems do you see now?

**Comment by oliver----** [comment]
Not real problems, only optimizations which are necessary for large documents.
The first thing is to address the transaction issue. This should improve it much already.
If necessary, I also need to optimize the event listening mechanism.

**Comment by Integral** [comment]
but what is transaction issue? what it consists of?

**Comment by oliver----** [comment]
Many types of editing involve multiple changes to the document, e.g., when you select a text block and start typing, first the selection gets deleted and then new text is inserted, and other things such as annotations get updated (and so on). To have this as a quasi atomic operation, in substance we start a transaction which does not affect any view while not finished. After everything is done the changes are applied in one pass to the real document which also updates all views etc.
E.g., if you paste a whole interview into the composer and you edit text somewhere you will see that it is very slow. This is because the transaction is implemented without any optimization.
Using that new implementation it will be very quick.

**Comment by Integral** [comment]
yeah, i see now, it's very slow...
how much time do you need?

**Comment by oliver----** [comment]
Not much... will be ready tomorrow.

**Comment by oliver----** [comment]
Being half through the transaction stuff I found some tricks to improve the existing solution.
So, I decided to go with the existing approach and implemented some 'optimizations' that make editing tolerable.

That said, I shift this work to the near future.

**Comment by oliver----** [comment]
Hmmm... on my machine running Windows the editing experience is still not very good, unfortunately.
Maybe I need to continue that transition earlier than later...

**Comment by Integral** [comment]
not very good? is it possible to work, what is your opinion?

**Comment by oliver----** [comment]
It is possible, but one would need to have to than to want to.
Personally, right now I would write in Word an copy over :(

**Comment by oliver----** [comment]
... and use it only for annotating.

**Comment by Integral** [comment]
i'll test it in different windows desktops as far as we'll have deployment
and you need much more time to fix it, yes?

**Comment by oliver----** [comment]
Yep.

**Comment by Integral** [comment]
approximately... ?

**Comment by oliver----** [comment]
Hard to say. I have made some progress, but many problems occurred...
Maybe within the next month.

**Comment by Integral** [comment]
auchhh... ///

**Comment by Integral** [comment]
@michael This is also kind of "critical" for us. But we'll wait.
