### ISSUE TITLE
Outline is not efficient enough for large documents

### ISSUE THREAD

**Issue by oliver----** [substance/archivist#47]
ATM, on every selection change the outlines (~scrollbars) get rerendered. With large documents as the interviews this is too slow.

This needs to be refactored, e.g., dropping the fine grained structure as we did it with Lens.
Probably more optimization could be needed.

@michael could you give some thoughts on it plz

**Comment by oliver----** [comment]
Deactivated the call to WriterView.updateOutline in onSelectionChange for now.

**Comment by michael** [comment]
Can we debounce the call, so it only gets called say every 500ms?

**Comment by oliver----** [comment]
Hmmm, not enough in that case, as we we have a lag every 500ms then, Which is typically on every first action (typing, cursor) and choking when moving cursor for scrolling.

**Comment by oliver----** [comment]
We have deactivated the inefficient part for now. A greater refactor is future.
