### ISSUE TITLE
Make subjects draggable

### ISSUE THREAD

**Issue by Integral** [substance/archivist#5]

**Comment by Integral** [comment]
done

**Comment by michael** [comment]
I just tested the drag and drop functionality: It's kind of hard to catch the right targets. E.g. when you move items on the same level, you immediately have them nested.. what if i just want to change the order? I think it needs more drop targets to specify the correct level on drag... i can see this is a pretty tricky task... there are so many edge cases that need to be handled... not sure anymore if we're on the right track with implementing that ourselves.

what is your feeling about the current drag+drop solution daniel? do you think it's enough?

**Comment by michael** [comment]
i think you should start to add some real world categories so we can test how this stuff works in a real scenario.

**Comment by Integral** [comment]
that was most easy solution, other would need much work, but it have all that we need I think...
we can't allow simple reorder because we can't fix it, there are no properties in our schema to know anything about order
yeah i should test now on current set of subjects

**Comment by michael** [comment]
What was the widget you were using before..? i just want to have a look once more. When we introduce collapsing we will have even more problems with drag and drop. E.g. drag an item on a closed tree node, then it should open up after some short delay.

**Comment by michael** [comment]
this one that i was using (while very ugly) does drag+drop well.

http://www.jstree.com/demo/

**Comment by Integral** [comment]
Yeah, I thought about this too... But it isn't so complex.
I used http://dbushell.github.io/Nestable/

**Comment by michael** [comment]
mhh should we go back to this? I don't remember all reasons why we started doing it ourselves. Well at that time I believed it can be done without drag+drop. Sorry I'm changing my mind so often :/
