### ISSUE TITLE
Test subject deletion / merging

### ISSUE THREAD

**Issue by michael** [substance/archivist#50]
How to test:

Preparation: 

- create a test subject subtree (1 main cat with 1 child, which has another sub child)
- assign all of those new subjects to some documents (using subject annotation feature)

Deletion:

- delete main subject in subject manager: should be rejected by system (you can not delete subjects that have childs)
- delete the most inner subject (this should be allowed): Now check the documents that were referencing this subject (if the subject tags are updated) check it in the ui but also in the database if everything is as it should be.

Merge: 
- merge main subject in subject manager: should be rejected by system (you can not delete subjects that have childs)
- merge the most inner subject with it's parent (this should be allowed): Now check the documents that were referencing this subject (if the subject tags are updated) check it in the ui but also in the database if everything is as it should be.

don't start with this. i will write GO when it's ready to test.

**Comment by michael** [comment]
GO!

**Comment by Integral** [comment]
testing delete
it removes term and it's parents, but not bracket (leaves empty bracket)
also after deleting term and refreshing page (in subject manager):
```21:00:59 web.1  | /Users/danielbeilinson/Documents/code/archivist/node_modules/mongoose/lib/utils.js:413
21:00:59 web.1  |         throw err;
21:00:59 web.1  |               ^
21:00:59 web.1  | ReferenceError: id is not defined
21:00:59 web.1  |     at /Users/danielbeilinson/Documents/code/archivist/controllers/db.js:231:33
21:00:59 web.1  |     at /Users/danielbeilinson/Documents/code/archivist/controllers/db.js:210:7
21:00:59 web.1  |     at _finally (/Users/danielbeilinson/Documents/code/archivist/node_modules/substance-util/src/async.js:96:64)
21:00:59 web.1  |     at /Users/danielbeilinson/Documents/code/archivist/node_modules/underscore/underscore.js:724:19
21:00:59 web.1  |     at /Users/danielbeilinson/Documents/code/archivist/node_modules/underscore/underscore.js:724:19
21:00:59 web.1  |     at process (/Users/danielbeilinson/Documents/code/archivist/node_modules/substance-util/src/async.js:33:16)
21:00:59 web.1  |     at /Users/danielbeilinson/Documents/code/archivist/node_modules/substance-util/src/async.js:51:7
21:00:59 web.1  |     at /Users/danielbeilinson/Documents/code/archivist/node_modules/underscore/underscore.js:724:19
21:00:59 web.1  |     at /Users/danielbeilinson/Documents/code/archivist/controllers/db.js:188:7
21:00:59 web.1  |     at Promise.<anonymous> (/Users/danielbeilinson/Documents/code/archivist/controllers/db.js:75:5)
21:00:59 web.1  | exited with code 8````

**Comment by michael** [comment]
I left empty bracket intentionally, to indicate that there was something.. maybe somebody afterwards just wants to assign the now right term. Empty brackets are no problem for the viewer later.. we will not display a bracket there, if no subjects are assigned.

The error you posted should be fixed now.

**Comment by michael** [comment]
works.
