### ISSUE TITLE
Implement subject manager using JSTree

### ISSUE THREAD

**Issue by michael** [substance/archivist#57]
Status:

- we managed to combine sort and dnd (dnb for siblings still works but immediately after the sort function reverts it, i guess this is fine behavior)
- context menu can be customized (I recommend that we make a cut+paste like workflow. we can call it merge and merge-into (it is only available if you first clicked merge)

![image](https://cloud.githubusercontent.com/assets/2931/5858776/09d5b2c6-a256-11e4-86f9-56ad78069d4f.png)

Decision: we will immediately send updates to the server for each operation, then we don't need a save button anymore. We will create a sample for you that has all new functionality and also data as we need it, and you can then attach it to your backbone model functions.

**Comment by Integral** [comment]
ok
sorry about me, i'm a little bit sleepy and overloaded today

**Comment by michael** [comment]
no worries. that's why we are strong and awake ;) 

we managed to make this look much nicer also without crappy icons.
![image](https://cloud.githubusercontent.com/assets/2931/5859057/bbe7e9ba-a257-11e4-85a1-fabbdfc88d11.png)

p.s. only oliver's stomach is hurting

**Comment by michael** [comment]
i will prepare everything and then we talk.. maybe tomorrow.. need a bit of time.

**Comment by Integral** [comment]
ok, thanks

**Comment by michael** [comment]
Going good here. things will become much much easier. will commit a version later. for editing the description we should use a modal dialog i think (that is triggered on doubleclick).. that way we can use the full space for nested subjects.

**Comment by michael** [comment]
@Integral modal dialog is good?

**Comment by Integral** [comment]
Yep, leave it to me, OK?

**Comment by michael** [comment]
Yep. I just pushed the initial implementation of the jstree-based subject manager. You can test by surfing to: http://localhost:5000/subject-manager

What needs to be done:

- convert subjects (backbone collection) to jsTree compatible structure (e.g. getTree method on the collection implementation)
- fill in server updates (u should reuse backbone model so you can just mode.save, model.delete etc.)

**Comment by michael** [comment]
Known issues: When a node is moved using drag and drop the event gets fired after the tree has been updated. That's too bad because now we can not undo the change.. i think for now it's okay to just prompt the user to reload the page and try again. if the server is working those cases shouldn't happen that often anyways...

**Comment by michael** [comment]
ahja and for desired tree structure see here:

https://github.com/substance/archivist/blob/fb0900c8def0cb5dd33261267ca14c1e4b626181/public/subject-manager/index.html#L20

you may want to reuse the code i used in the subjects-panel for converting the flat format into a hierarchical tree:

https://github.com/substance/archivist/blob/master/src/panels/subjects/subjects_controller.js#L130
https://github.com/substance/archivist/blob/master/src/panels/subjects/subjects_controller.js#L15

**Comment by Integral** [comment]
ok, will do something here tomorrow or on saturday

**Comment by Integral** [comment]
so, tree in backbone view now
now i need to connect it with models

few questions:
1) did you try to use search here?
2) you have state variable, i want to make it view instance property, is there any way to pass context to itemsFunc?

**Comment by michael** [comment]
1) i guess search just needs a textbox to be connected. i will activate it later.
2) i think you can bind itemsfunc it just returns an object finally, also you could make it an instance method of your backbone view or so. if you can't get it to work i will connect it later.

**Comment by Integral** [comment]
Rename and moving terms is working now. Except making term root. There is a problem here... jSTree set parent: '#', @michael have you got any quick suggestions where i could change this?

**Comment by Integral** [comment]
@michael, i manage to escape of mentioned problems, but i run into it again, i need access to view in itemsFunc (which is view method) to get model and remove it...

**Comment by Integral** [comment]
i also need this to place edir description in context menu and open form in modal, can't do this without access to collection/model/view, now context is window...

**Comment by michael** [comment]
I still see the old subjects manager localhost:5000/subjects.

On server start I get an error regarding jstree:

```
Cannot find module 'jstree' from '/Users/michael/projects/substance/archivist_web/client/platform'
```

**Comment by Integral** [comment]
@michael, that's because you need to install jstree
go to client/platform and ```run npm install```

**Comment by Integral** [comment]
@michael just found solution, sorry :)

**Comment by michael** [comment]
Sorry i was not responding yesterday evening. What's current status? I still didn't manage to install jstree with npm. :/ same error.

**Comment by michael** [comment]
I installed manually with npm install jstree. But now i get error in client code, jQuery not defined :/ i don't get this client side module stuff with bundling etc. can you have a look.. everything is broken now :(

**Comment by Integral** [comment]
merge works

**Comment by Integral** [comment]
description works
