### ISSUE TITLE
Implicit maintanance mode

### ISSUE THREAD

**Issue by michael** [substance/archivist#62]
While working on the jstree-based subject manager I had some ideas how we can make the maintenance mode implicit, so we don't have do so many actions for doing simple updates.

First of all, most options don't touch any documents so they don't require a maintenance mode. Those are:

- move subject
- create subject
- rename subject

So you will be able to perform those actions any time without extra action. 

Now how to go about the destructive actions:

- delete subject
- merge subject

When user clicks 'delete' or 'merge into' we do the following:

- tell the user that this is a heavy action, that may take a while to complete and while it's running it will interrupt the writing process of editors (=maintenance mode).
- if the user confirms the services mergeSubject/deleteSubject will turn maintenance mode on automatically and turn it off again after the operation has been completed. 
- turning on maintenance mode implicitly creates a backup first, so if during our massive operation something goes wrong we can restore the state from before turn off maintenance mode again but let the user know the operation was not applied.

This requires some smartness on the server side but I think it's the best possible solution because it doesn't add anything extra to the user interface, and also it's secure. what we get here is a safe transaction mechanism:

- turn maintenance mode on (start transation)
- make batch updates
- turn maintenance mode off (commit transaction when no errors, rollback transaction when there was an error)

**Comment by Integral** [comment]
but users'll still have problems if they were editing outdated doc

**Comment by michael** [comment]
That's only true for users who are editing docs that were affected during the operation. So it may not happen so often at all.. There's no easy way to solve this completely... we would need a conflict resolution mechanism but that's out of scope for now. I will look into autosave soon, this will also make the situation better (since we don't have uncommitted docs around).

**Comment by michael** [comment]
yeh that's what i thought too... and we save some buttons that would confuse users.

**Comment by michael** [comment]
@Integral can you check what needs to be done to trigger generating a backup. is it possible.. and if backup is created, how to restore it programmatically?

**Comment by Integral** [comment]
yeah, autosave'll make this not so bad, we could implement message later, with first autosave, just based on __v

**Comment by michael** [comment]
don't understand.. what you mean with message?

**Comment by Integral** [comment]
well, it's a trivial task, but not so easy in the same time
first of all mongodb have shell commands mongodump and mongorestore, so we could use smth like exec to do it, but we also need to read directory with this files
i also found this project: https://github.com/timisbusy/dumpstr, but it can't restore...

**Comment by Integral** [comment]
@michael i mean notification

**Comment by michael** [comment]
I saw that compose.io has a backup/restore feature.. can this be used maybe? 

![image](https://cloud.githubusercontent.com/assets/2931/5880219/d0cf7a66-a336-11e4-9a92-2ebed1b3360e.png)

**Comment by Integral** [comment]
hey, you're right: https://docs.compose.io/rest-api/2014-06/backups.html

**Comment by Integral** [comment]
but it's not the best solution, we will run into service dependency

**Comment by michael** [comment]
is there a way to duplicate the entire documents collection? so we have documents_backup

**Comment by michael** [comment]
more light way of backup.. but enough for rollback...

**Comment by Integral** [comment]
there is special function for this in mongo shell, we could use it through eval, but it's not supergood

**Comment by michael** [comment]
but what if that is done manually.. list all doc ids.. and then copy to a new collection one by one?

**Comment by Integral** [comment]
yep, actually i have some useful drafts for real batch with limit processes here...

**Comment by michael** [comment]
this is a critical issue. if backup is too hard to solve for now we have to be aware it could mean data loss (like no way to undo a batch operation). If possible manual copy-restore workflow of documents would be a good solution.

**Comment by michael** [comment]
I can look into this too. Let's see how much issues we all will have left at the end of the day.

**Comment by Integral** [comment]
from skype:

admin clicks on delete subject:
- backup is made
- maintenance mode is switched on
- changes are applied                 (if somebody tries to save at that time, he will see: Sorry not possible because system is in maintenance mode error)
- maintenance mode is switched off

**Comment by michael** [comment]
I will implement this on the server-side today.

**Comment by Integral** [comment]
Sorry, have a lot of sudden work yesterday. I just finished with jstree (merge, modal description)! Wooo!!!! :beers: 
So, let me help you here please! :pray: I'll discover easiest ways for making collection backup.

**Comment by michael** [comment]
that's so nice of you. :) So yeah we can split work a bit. Essentially what I need is a db.backupDocuments() method as well as a db.restoreDocuments() method. :) So if you could do that for me I will make the rest and test.

I'd be curious how you will do it, because it seems that using some native mongo API would be the easiest. Mongoose has everything tied to schema definitions that belong to one collections, which makes things a bit harder to access. I was wondering if the document schema could just be reused, so you could save on the model but telling that it should use a different collection. Hm... or you have to create a copy of the schema and call it DocumentBackup?

**Comment by Integral** [comment]
Why do you need to use other collection? As I understand second collection must be shadow copy for a restoring?

**Comment by michael** [comment]
exactly.. just don't know what is the best solution. you would store them in the same collection? well.. you make decision here. i started integrating stub functions.

**Comment by Integral** [comment]
ok, already working on this

**Comment by Integral** [comment]
ok
so now you can use ```db.makeSubjectsBackup(cb)``` and ```db.restoreSubjectsBackup(cb)```
```cb``` may return ```err```, check it

**Comment by michael** [comment]
oke, but we actually need backup of documents, not subjects.

**Comment by michael** [comment]
can you implement the same for docs?

**Comment by michael** [comment]
don't delete subjects backup..  we can also use it

**Comment by Integral** [comment]
great news :) i'm crazy man :)

**Comment by Integral** [comment]
sorry again
```db.makeDocumentsBackup(cb)``` and ```db.restoreDocumentsBackup(cb)``` at your service now

**Comment by michael** [comment]
Working for deleteSubject. It just takes a while to complete.. (could be because of my slow internet connection). Daniel, can you try the deletion how long it takes for you?

**Comment by Integral** [comment]
yes, 2.7 seconds

**Comment by michael** [comment]
it will be faster in the deployed version. when running node locally every doc needs to travel through the web 2 times. the db should be close to the node server in production. Is compose.io fast in combination with heroku? or should we consider using some heroku option for mongo?

**Comment by michael** [comment]
for me it took 99s btw.

**Comment by Integral** [comment]
heroku have no mongo service, but it provide compose as add-on, so must be
ok

**Comment by michael** [comment]
ok. if too slow we use mysql ;)

**Comment by michael** [comment]
Done. Good work mr beilinson! :+1:

**Comment by oliver----** [comment]
System seems to be in maintainance mode all the time.. did it get stuck?

**Comment by Integral** [comment]
@michael, switched off through db directly. Any ideas why it was turned on? I also noticed that user attribute was null.

**Comment by michael** [comment]
May be a bug in the transaction method. Will test it more thorougly tomorrow.

**Comment by michael** [comment]
@Integral the user attribute is no longer used/needed, since maintenance mode is turned on and off during one operation.

**Comment by Integral** [comment]
yes, of course, sorry!

**Comment by michael** [comment]
fixed in master.
