### ISSUE TITLE
Edge case identified related to subject deletion

### ISSUE THREAD

**Issue by michael** [substance/archivist#63]
- user edits a document with no subjects annotations yet (but subjects panel has all subjects available for selecting them)
- admin deletes subject_25
- user adds subject_25 to the doc (using the outdated subjects-list)
- user hits save
- a reference to a non-existing subject will be stored on the server :(

Solution 1: we make all docs dirty after subject deletion so a reload is forced
Solution 2: fetch all subjects from server every time you click on the edit button of a subject annotation
Solution 3: on save we can verify all subject_references if they point to existing targets. if target does not exist we can delete the ref. finally we return the cleaned up doc to the user.

**Comment by Integral** [comment]
hm, maybe we also could poll some status doc to see last time of maintenance mode was turned on, then we could reload all subjects if we discovered newest time, or just reload after poll will discover changing of mode, is it possible?

**Comment by michael** [comment]
Maybe something like that.. needs a bit of thinking. I want to solve this all on paper first.. also in combination with autosave.

**Comment by michael** [comment]
I think after some destructive operation we should invalidate all docs that are out there and force a reload. people won't loose data if we have autosave.

was thinking of some smarter merging mechanism on the client, but it only helps in that case.. whenever somebody else does concurrent edits we have an unsolveable problem anyways... so we do save often.. and we do it first one wins.

**Comment by Integral** [comment]
will they loose current state (position etc)?

**Comment by michael** [comment]
position? i have to go now.. talk tomorrow!

**Comment by Integral** [comment]
ok, let's try tomorrow

**Comment by michael** [comment]
OK i have solution for this now so we don't need to enforce a reload when the doc is not affected directly:

- we will maintain a version of the subjects database.. which means every time you make a change to the subject database the version gets counted up.
- after a doc has been saved successfully we will return not only the new doc version but also the subjects version.
- if they don't match we will refetch the subjects and re-render the current subject-panel state

it's a bit of extra work and special handling but i think this is useful in general because we retrieve subject changes more regularly. in current solution the only way to get the updated set of subjects is using reload.

i could imagine this subject fetching being triggered every 10 minutes automatically but i'm afraid of side effects this could cause (e.g. the side panel jumps even if the user didn't do anything) i don't want to have concurrent intervals (like autosave and fetch subjects).

**Comment by michael** [comment]
This is solved with subjectDBVersion synchronization.
