### ISSUE TITLE
When reload gets necessary (conflict situation) we should persist cursor position in state

### ISSUE THREAD

**Issue by michael** [substance/archivist#65]
.... so on relead we can reconstruct the cursor position.

That means that when an error occurs (bloody toolbar) the selection gets persisted (pls verify if valid).

**Comment by Integral** [comment]
hm... not sure that i understand correctly, did you mean that i should return url parameters with error?

**Comment by michael** [comment]
nono.. this is placholder issue for oliver. Sorry i was accidently assigning you.

**Comment by oliver----** [comment]
window.onbeforeunload it is
