### ISSUE TITLE
Create dialog for delete and merge operations

### ISSUE THREAD

**Issue by michael** [substance/archivist#67]
Since we have pretty heavy operations now we should provide a popup window to warn the user that they're about to execute a long-running operations which puts the system into maintenance mode for some time.

It should look like this:

![image](https://cloud.githubusercontent.com/assets/2931/5924015/5a6e4792-a658-11e4-898d-72b1fa8d4d14.png)

And similar for merge subjects. What is also important is proper error messages. Currently one generic error message is shown when a delete fails. Maybe we should display the error or success message within that popup. Or let's say on success the popup gets closed, and on error you get the error message and you can retry.

**Comment by Integral** [comment]
oh, yes! done!
