### ISSUE TITLE
Use automatic CSS linter

### ISSUE THREAD

**Issue by oliver----** [substance/archivist#71]
It cost me hours yesterday to spot this syntax error.

https://github.com/substance/article/blame/master/nodes/strong/strong.css#L5

It appeared in the bundle only, as it blocked all rules after that in the bundle - which are almost all.

@Integral to you know a gulp solution for that?

**Comment by oliver----** [comment]
It is https://www.npmjs.com/package/gulp-csslint

**Comment by oliver----** [comment]
I will try to integrate gulp with CJSServer - in future.

**Comment by Integral** [comment]
yes, there are numbers of such projects (for example for less if you'll switch)
