### ISSUE TITLE
Try to replace duo

### ISSUE THREAD

**Issue by Integral** [substance/archivist#72]
with https://www.npmjs.com/package/gulp-import-css

**Comment by oliver----** [comment]
Done.

**Comment by Integral** [comment]
really? you did it for platform's index.css?

**Comment by oliver----** [comment]
I did it... hopefully nothing is broken (?)

**Comment by oliver----** [comment]
did it only  for platform/index.css... is it the only one?

**Comment by Integral** [comment]
super! it's working! i also removed duo and other dependencies from gulp config and package.json
