### ISSUE TITLE
Split up views

### ISSUE THREAD

**Issue by Integral** [substance/archivist#73]
Split up views on different files to avoid chaos. Maybe we should also gather models/views/collection on same folders based on entity type? @michael, @oliver---- what do you think?

**Comment by michael** [comment]
definitely. views.js is getting too big. i would start this work after the release though. we will be busy with some elife/plos etc. stuff in the coming weeks so ideally you can continue and we come back to help you with the next iteration. i guess it will be implementing the metadata panel?

**Comment by Integral** [comment]
i have also google-spredsheet scipts stuff
then my next step would be locations i guess, not sure that i can help you with metadata panel, although i'll gladly do it if you find me useful here
