### ISSUE TITLE
Make notifications stackable

### ISSUE THREAD

**Issue by Integral** [substance/archivist#76]
it seems they aren't now

**Comment by michael** [comment]
We need a way to send blocking notifications.. e.g. in subject manager when you move an entry and you receive an error we should force a reload.. because currently jstree applied that change anyway... so the client model gets out of sync with the server.

**Comment by Integral** [comment]
we could always force reload, but it'll remove notification

**Comment by michael** [comment]
i would display a confirm dialog containing the error message. maybe alert() also does it. this shouldn't happen so often, but when there are concurrent operations on the subject manager it may occur and we should protect against it.

**Comment by michael** [comment]
i will take care of subject manager errors using alert followed by a hard reload.

**Comment by michael** [comment]
Except for merge and delete which require modal dialogs.
