### ISSUE TITLE
Make authentication

### ISSUE THREAD

**Issue by Integral** [substance/archivist#8]
Implement google oauth. Store sessions in mongodb. Protect API.

**Comment by Integral** [comment]
Hey @michael and @oliver---- !
You should make npm install next time, there are new dependencies. Platform'll ask you to login through google account. First time it won't pass you, but will store your profile. So, you'll need to go to [users collection](https://app.compose.io/beilinson-gmail-com/deployments/gol-donate-deployment/mongodb/databases/archivist/collections/users/documents) and set ```access``` and ```super``` properties to ```true```.
Actually it's now protect only jade routes. But I'll protect apis too.
There 2 function currently:
```oauth.ensureAuthenticated``` - it'll just check whether or not you are authenticated and you can only pass authentication if you have ```access: true``` 
```oauth.ensureSuperAuth``` - this function will check whether or not you have ```user.access && user.super```. Let's use it for extra dangerous operations like delete document, merge terms etc.

Oh yeah, and you can pass this functions to express routes. Just like this:
```
rest.route('/documents')
  .post(oauth.ensureAuthenticated, createDocument)
```

**Comment by michael** [comment]
Updated and it works now.. just a few times I had errors which went away when I did a reload. You think that was a temporary problem?

**Comment by Integral** [comment]
What errors? Where it leads you?

**Comment by michael** [comment]
at the very beginning i saw a stacktrace.. but went away after reload.. i should have tracked it :/ then first round went smooth when i clicked login with google and then it said the user must wait for activation. So far so good so i activated the user in the db. and then reloaded. it was asking again for logging in via google so i did.. but then i was not in.. i was sent back to the login page again.. i did this a second time and then it worked and i saw the dashboard.

**Comment by Integral** [comment]
Let's keep eyes on this.
