### ISSUE TITLE
Critical: Pasting summary leads to loss of other fields

### ISSUE THREAD

**Issue by Integral** [substance/archivist#84]
If you'll try to paste summary other title, second summary and body'll disappeared. See [this document](http://archivist-app.herokuapp.com/archivist.html#state=composer.main;0.path=54ce2117a75590030053a009;1.contextId=toc) for example.

Was able to reproduce it in mac, windows/chrome, firefox.

Possible solution: hide it for some time and then open in metadata panel.

**Comment by michael** [comment]
oh that's a bad one. @oliver---- seems like we are loosing the cover node completely.
