### ISSUE TITLE
Hot keys not working in FF

### ISSUE THREAD

**Issue by Integral** [substance/archivist#87]
ctrl-v, ctrl-c, ctrl-z etc not working.

Was able to reproduce it in both windows and mac versions of firefox.

**Comment by michael** [comment]
There's no FF guaranteed FF support atm. Didn't we say we make it Chrome exclusive?

**Comment by Integral** [comment]
@michael I guess we not discussed this. But i'm sure that all firefox bugs must be in extra low priority. Of course not for reader ;)

**Comment by michael** [comment]
jeh. please don't create FF-related editor issues for now.. we won't be able to address them anytime soon.

**Comment by Integral** [comment]
ok, closing this

**Comment by michael** [comment]
(u on skype?)
