### ISSUE TITLE
Subjects actions wrong css 

### ISSUE THREAD

**Issue by Integral** [substance/archivist#9]
See:
![](http://cl.ly/image/313k0u003a0c/Screen%20Shot%202015-01-13%20at%2016.09.48.png)

**Comment by michael** [comment]
Fixed. Do

```js
substance --update
```

**Comment by Integral** [comment]
Hm, are you sure? Can't see any changes.

**Comment by michael** [comment]
Maybe you have to restart, since i updated project.json to exclude archivist.css, which is no longer needed.

**Comment by Integral** [comment]
It's here again.
